name: .NET CI

on:
  push:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Create temporary console project
      run: dotnet new console -n RendApp

    - name: Build project
      run: dotnet build RendApp --configuration Release

    - name: Run app with test input
      run: |
        echo -e "Hello\nCyber Security\nBye" | dotnet run --project RendApp --no-build
