name: .NET CI

on:
  push:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Create temp project
      run: dotnet new console -n RendApp

    - name: Replace Program.cs
      run: |
        cp Program.cs RendApp/Program.cs

    - name: Build project
      run: dotnet build RendApp --configuration Release

    - name: Run app (test input)
      run: |
        echo -e "Hello\nBye" | dotnet run --project RendApp --no-build
